# Generated by Django 4.2.4 on 2023-09-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0002_alter_statevector_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statevector",
            name="time",
        ),
        migrations.AddField(
            model_name="statevector",
            name="icao24",
            field=models.CharField(default="", unique=True),
        ),
    ]
